# 自定义属性
com:
  zhang:
    name: 一直、很安静

spring:
  profiles:
    active: dev # 开发环境选择
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.3.98.153:3306/test01?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=true
    username: ruixin
    password: Huntkey11!