apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: modeler-client-deployment
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        name: modeler-client
    spec: 
      containers: 
        - name: modeler-client
          image: 10.3.98.241/biz-modeler/modeler-client
          ports: 
            - containerPort: 2001
#           resources: 
#             limits: 
#             cpu: 0.5
#             memory: 512Mi
#          volumeMounts:
#            - mountPath: /sceo-log/log
#              name: go-logs
#      volumes:
#      - name: go-logs
#        hostPath:
#          path: /sceo-log/log