apiVersion: v1
kind: Service
metadata:
  name: modeler-client-service
spec:
  type: NodePort
  ports:
    - port: 2001
      nodePort: 30001
      targetPort: 2001
      protocol: TCP
  selector:
    name: modeler-client