server:
  port: 9000
spring:
  application:
    name: biz-hr-method-zy
  jmx:
    enabled: false
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false #调试用 超时不熔断
hr:
  lvl:
    step: 3