spring:
  application:
    name: commonService-provider
  messages:
    encoding: UTF-8
    basename: i18n/commom
  userauthentication:
    usernane: hjsc
    password: 4gg2fmq9
    visa: 【嘉源锐信】
    msgfmt:
    ext:   
           
    