apiVersion: v1
kind: Service
metadata:
  name: modeler-provider-service
spec:
  type: NodePort
  ports:
    - port: 2002
      nodePort: 30002
      targetPort: 2002
      protocol: TCP
  selector:
    name: modeler-provider