server:
  port: 9100 # 端口号

spring:
  application:
    name: biz-purchase-method-zy # 服务名
  jmx:
      enabled: false # 关闭JMS监控

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false # 调试用 超时不熔断