apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hr-method-provider
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hr-method-provider
    spec:
      containers:
        - name: hr-method-provider
          image: 10.3.98.241/biz-hr-method/biz-hr-method-provider
          ports:
            - containerPort: 9000
#           resources: 
#             limits: 
#             cpu: 0.5
#             memory: 512Mi
#          volumeMounts:
#            - mountPath: /sceo-log/log
#              name: go-logs
#      volumes:
#      - name: go-logs
#        hostPath:
#          path: /sceo-log/log