server:
  port: 8888
spring:
  application:
    name: driver-service-demo
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://10.3.98.154:1111/eureka/ #注册中心地址
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 50000
