server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client: #通过以下两个配置false表示是eureka server，不是eureka client
    registerWithEureka: false #表示是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false。
    fetchRegistry: false #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。
  serviceUrl:
    defaultZone: http://localhost:8761/eureka # http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server交互的地址，多个地址可使用 , 分隔。